// Auto generated component declarations
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Circle: typeof import('vue3-baidu-map-gl')['Circle']
    CityList: typeof import('vue3-baidu-map-gl')['CityList']
    Control: typeof import('vue3-baidu-map-gl')['Control']
    Copyright: typeof import('vue3-baidu-map-gl')['Copyright']
    Label: typeof import('vue3-baidu-map-gl')['Label']
    Location: typeof import('vue3-baidu-map-gl')['Location']
    Map: typeof import('vue3-baidu-map-gl')['Map']
    Marker: typeof import('vue3-baidu-map-gl')['Marker']
    Navigation3d: typeof import('vue3-baidu-map-gl')['Navigation3d']
    Polygon: typeof import('vue3-baidu-map-gl')['Polygon']
    Polyline: typeof import('vue3-baidu-map-gl')['Polyline']
    Scale: typeof import('vue3-baidu-map-gl')['Scale']
    Zoom: typeof import('vue3-baidu-map-gl')['Zoom']
    install: typeof import('vue3-baidu-map-gl')['install']
    version: typeof import('vue3-baidu-map-gl')['version']
    InfoWindow: typeof import('vue3-baidu-map-gl')['InfoWindow']
    Marker3d: typeof import('vue3-baidu-map-gl')['Marker3d']
    Prism: typeof import('vue3-baidu-map-gl')['Prism']
    BCircle: typeof import('vue3-baidu-map-gl')['Circle']
    BCityList: typeof import('vue3-baidu-map-gl')['CityList']
    BControl: typeof import('vue3-baidu-map-gl')['Control']
    BCopyright: typeof import('vue3-baidu-map-gl')['Copyright']
    BInfoWindow: typeof import('vue3-baidu-map-gl')['InfoWindow']
    BLabel: typeof import('vue3-baidu-map-gl')['Label']
    BLocation: typeof import('vue3-baidu-map-gl')['Location']
    BMap: typeof import('vue3-baidu-map-gl')['Map']
    BMarker: typeof import('vue3-baidu-map-gl')['Marker']
    BMarker3d: typeof import('vue3-baidu-map-gl')['Marker3d']
    BNavigation3d: typeof import('vue3-baidu-map-gl')['Navigation3d']
    BPolygon: typeof import('vue3-baidu-map-gl')['Polygon']
    BPolyline: typeof import('vue3-baidu-map-gl')['Polyline']
    BPrism: typeof import('vue3-baidu-map-gl')['Prism']
    BScale: typeof import('vue3-baidu-map-gl')['Scale']
    BZoom: typeof import('vue3-baidu-map-gl')['Zoom']
    Binstall: typeof import('vue3-baidu-map-gl')['install']
    Bversion: typeof import('vue3-baidu-map-gl')['version']
  }
}
export {}
