// Auto generated component declarations
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Circle: typeof import('vue3-baidu-map-gl')['Circle']
    BmCircle: typeof import('vue3-baidu-map-gl')['Circle']
    CityList: typeof import('vue3-baidu-map-gl')['CityList']
    BmCityList: typeof import('vue3-baidu-map-gl')['CityList']
    Control: typeof import('vue3-baidu-map-gl')['Control']
    BmControl: typeof import('vue3-baidu-map-gl')['Control']
    Copyright: typeof import('vue3-baidu-map-gl')['Copyright']
    BmCopyright: typeof import('vue3-baidu-map-gl')['Copyright']
    Label: typeof import('vue3-baidu-map-gl')['Label']
    BmLabel: typeof import('vue3-baidu-map-gl')['Label']
    Location: typeof import('vue3-baidu-map-gl')['Location']
    BmLocation: typeof import('vue3-baidu-map-gl')['Location']
    Map: typeof import('vue3-baidu-map-gl')['Map']
    BmMap: typeof import('vue3-baidu-map-gl')['Map']
    Marker: typeof import('vue3-baidu-map-gl')['Marker']
    BmMarker: typeof import('vue3-baidu-map-gl')['Marker']
    Navigation3d: typeof import('vue3-baidu-map-gl')['Navigation3d']
    BmNavigation3d: typeof import('vue3-baidu-map-gl')['Navigation3d']
    Polygon: typeof import('vue3-baidu-map-gl')['Polygon']
    BmPolygon: typeof import('vue3-baidu-map-gl')['Polygon']
    Polyline: typeof import('vue3-baidu-map-gl')['Polyline']
    BmPolyline: typeof import('vue3-baidu-map-gl')['Polyline']
    Scale: typeof import('vue3-baidu-map-gl')['Scale']
    BmScale: typeof import('vue3-baidu-map-gl')['Scale']
    Zoom: typeof import('vue3-baidu-map-gl')['Zoom']
    BmZoom: typeof import('vue3-baidu-map-gl')['Zoom']
    install: typeof import('vue3-baidu-map-gl')['install']
    Bminstall: typeof import('vue3-baidu-map-gl')['install']
    version: typeof import('vue3-baidu-map-gl')['version']
    Bmversion: typeof import('vue3-baidu-map-gl')['version']
    InfoWindow: typeof import('vue3-baidu-map-gl')['InfoWindow']
    BmInfoWindow: typeof import('vue3-baidu-map-gl')['InfoWindow']
    Marker3d: typeof import('vue3-baidu-map-gl')['Marker3d']
    BmMarker3d: typeof import('vue3-baidu-map-gl')['Marker3d']
    Prism: typeof import('vue3-baidu-map-gl')['Prism']
    BmPrism: typeof import('vue3-baidu-map-gl')['Prism']
  }
}
export {}
